name: fridgeai
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+2  # For capturing images
  image_picker: ^1.1.2  # For picking images from the gallery
  http: ^1.2.2  # For making API requests
  flutter_dotenv: ^5.2.1  # For managing API keys securely
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.2
  shared_preferences: ^2.3.5
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true