name: fridgeai
description: "You can use this app to keep track of the food in your fridge and get recipe suggestions based on the ingredients you have."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+2
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.2
  shared_preferences: ^2.3.5
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Add this section
  assets:
    - .env
    # Add any other assets you need like images here
    # - assets/images/
    # - assets/icons/